name: mobile
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  go_router: ^12.1.0
  flutter_secure_storage: ^9.0.0
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  intl: ^0.19.0
  file_picker: ^6.1.1
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.2
  lucide_icons: ^0.257.0
  flutter_native_splash: ^2.4.7
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  freezed: ^2.4.7
  riverpod_generator: ^2.3.9

flutter:
  uses-material-design: true
